### ISSUE TITLE
Crash after adding second device

### ISSUE THREAD

**Issue by StijnOostdam** [StijnOostdam/Winleafs#73]
Was able to get it to launch with the new release!

&#x200B;

I have two discrete nanoleaf panel sets on separate walls.

I then hit Add Device and added my other cluster, but it didn't appear in the dropdown box.

I closed the app, attempted to reopen it, and it wouldn't again. I have to delete settings.txt and reboot (just deleting settings.txt won't fix), then it'll let me re-add one cluster of panels again. Same thing happens when I try to add my second one.

&#x200B;

Log:  [https://pastebin.com/LVca0cmv](https://pastebin.com/LVca0cmv)

**Comment by StijnOostdam** [comment]
Update: I found that rebooting after adding the second panel caused it to appear in the dropdown box.

**Comment by StijnOostdam** [comment]
019-03-31 18:10:12.5616|INFO|Winleafs.Wpf.Views.Setup.SetupWindow|Discovered following device: Light-Panels-52-cb-00, IPs: System.Collections.Generic.List`1[System.Net.IPAddress], Port: 16021
2019-03-31 18:10:12.5866|INFO|Winleafs.Wpf.Views.Setup.SetupWindow|Discovered following device: Light-Panels-52-ca-f7, IPs: System.Collections.Generic.List`1[System.Net.IPAddress], Port: 16021
2019-03-31 18:10:30.1688|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.200.8:16021/, URL: api/v1/pdWIX5HxrUiTdI04L6kzbIYu1cAdWhOI/identify, Method: PUT, Body:
2019-03-31 18:10:30.1788|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.200.8:16021/, URL: api/v1/pdWIX5HxrUiTdI04L6kzbIYu1cAdWhOI//effects/effectsList, Method: GET, Body:
2019-03-31 18:10:35.9327|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.200.8:16021/, URL: api/v1/pdWIX5HxrUiTdI04L6kzbIYu1cAdWhOI//state/on, Method: GET, Body:
2019-03-31 18:10:35.9697|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.200.8:16021/, URL: api/v1/pdWIX5HxrUiTdI04L6kzbIYu1cAdWhOI/panelLayout/layout, Method: GET, Body:
2019-03-31 18:10:35.9817|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.200.8:16021/, URL: api/v1/pdWIX5HxrUiTdI04L6kzbIYu1cAdWhOI/panelLayout/globalOrientation, Method: GET, Body:
2019-03-31 18:10:36.0228|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.200.8:16021/, URL: api/v1/pdWIX5HxrUiTdI04L6kzbIYu1cAdWhOI/panelLayout/layout, Method: GET, Body:
2019-03-31 18:10:36.0228|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.200.8:16021/, URL: api/v1/pdWIX5HxrUiTdI04L6kzbIYu1cAdWhOI/panelLayout/globalOrientation, Method: GET, Body:
2019-03-31 18:10:42.8203|INFO|Winleafs.Wpf.Views.Setup.SetupWindow|Discovered following device: Light-Panels-52-cb-00, IPs: System.Collections.Generic.List`1[System.Net.IPAddress], Port: 16021
2019-03-31 18:11:03.0632|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.200.10:16021/, URL: api/v1/MlhYGoqHlKQJNwPXFh8SFUYttZc4njyT/identify, Method: PUT, Body:
2019-03-31 18:11:03.0702|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.200.10:16021/, URL: api/v1/MlhYGoqHlKQJNwPXFh8SFUYttZc4njyT//effects/effectsList, Method: GET, Body:
2019-03-31 18:11:10.4687|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.200.10:16021/, URL: api/v1/MlhYGoqHlKQJNwPXFh8SFUYttZc4njyT/state, Method: PUT, Body: {"brightness": {"value":0}}
2019-03-31 18:11:10.5484|ERROR|Winleafs.Wpf.Api.Orchestrator|Enabling effect failed for device Bed Wall with trigger effect
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at Winleafs.Wpf.Api.Orchestrator.<ActivateEffect>d__14.MoveNext()
2019-03-31 18:11:35.9422|INFO|Winleafs.Api.Endpoints.NanoleafEndpoint|Sending following request: Address: http://192.168.200.8:16021/, URL: api/v1/pdWIX5HxrUiTdI04L6kzbIYu1cAdWhOI//state/on, Method: GET, Body:
